version: '3.7'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
  db:
    image: solr:8.1.1
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh 
      - solr-precreate
      - gettingstarted
  app:
    build: .
    command: "npm start"
    ports:
      - "4200:4200" 
      - "49153:49153"
    expose:
      - "4200" 
      - "49153"
    volumes:
      - "./:/app/"
    dependes:
      - db  
          