version: '3.7'
services:
  db:
    build:
      context: ./solr
    ports:
      - "8983"
      - "8984:8983"
    entrypoint:
      - docker-entrypoint.sh 
      - solr-precreate
      - gettingstarted
      - /tmp/gettingstarted
  app:
    build:
      context: .
    depends_on:
      - db  
    ports:
      - "4200:4200"
    entrypoint:
      - npm
      - start
    environment:
      - SOLR_DB=http://db:8983
    

          