version: '3.7'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
  db:
    build:
      context: ./solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh 
      - solr-precreate
      - gettingstarted
       - /tmp/gettingstarted
  app:
    build: .
    command: "npm start"
    ports:
      - "4200:4200" 
    expose:
      - "4200" 
    volumes:
      - "./:/app/"
    dependes:
      - db  
          