version: '3.7'
services:
  db:
    build:
      context: ./solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh 
      - solr-precreate
      - gettingstarted
      - /tmp/gettingstarted
    

          